"""pipeline tables

Revision ID: d49c6650494c
Revises: 0003_drop_scan_results_unique
Create Date: 2026-07-13 02:19:00.260926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d49c6650494c"
down_revision: Union[str, None] = "0003_drop_scan_results_unique"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column(
            "pipeline_type",
            sa.Enum(
                "DEFAULT_FILE_PROCESSING",
                "EXTENDED_FILE_PROCESSING",
                name="pipelinetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                name="processingtaskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_processing_tasks_file_id", "processing_tasks", ["file_id"], unique=False
    )
    op.create_index(
        "ix_processing_tasks_pipeline_type",
        "processing_tasks",
        ["pipeline_type"],
        unique=False,
    )
    op.create_index(
        "ix_processing_tasks_status", "processing_tasks", ["status"], unique=False
    )
    op.create_table(
        "task_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("processing_task_id", sa.Integer(), nullable=False),
        sa.Column(
            "processor",
            sa.Enum(
                "METADATA_EXTRACTOR",
                "SIZE_CHECKER",
                "EXTENSION_VALIDATOR",
                "MIME_VALIDATOR",
                "ANTIVIRUS_SCANNER",
                "YARA_SCANNER",
                name="processortype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "WARNING",
                "FAILED",
                "SKIPPED",
                name="taskexecutionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["processing_task_id"], ["processing_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_executions_processing_task_id",
        "task_executions",
        ["processing_task_id"],
        unique=False,
    )
    op.create_index(
        "ix_task_executions_processor", "task_executions", ["processor"], unique=False
    )
    op.create_index(
        "ix_task_executions_status", "task_executions", ["status"], unique=False
    )
    op.drop_table("scan_results")
    op.drop_table("alerts")
    op.add_column(
        "files",
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PROCESSING",
                "OK",
                "WARNING",
                "FAILED",
                name="filestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_files_created_at", "files", ["created_at"], unique=False)
    op.create_index("ix_files_status", "files", ["status"], unique=False)
    op.drop_column("files", "requires_attention")
    op.drop_column("files", "scan_status")
    op.drop_column("files", "processing_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "processing_status",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "files",
        sa.Column(
            "scan_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "files",
        sa.Column(
            "requires_attention", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index("ix_files_status", table_name="files")
    op.drop_index("ix_files_created_at", table_name="files")
    op.drop_column("files", "status")
    op.create_table(
        "alerts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "file_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column("level", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("alerts_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("alerts_pkey")),
    )
    op.create_table(
        "scan_results",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "file_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("scan_results_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scan_results_pkey")),
    )
    op.drop_index("ix_task_executions_status", table_name="task_executions")
    op.drop_index("ix_task_executions_processor", table_name="task_executions")
    op.drop_index("ix_task_executions_processing_task_id", table_name="task_executions")
    op.drop_table("task_executions")
    op.drop_index("ix_processing_tasks_status", table_name="processing_tasks")
    op.drop_index("ix_processing_tasks_pipeline_type", table_name="processing_tasks")
    op.drop_index("ix_processing_tasks_file_id", table_name="processing_tasks")
    op.drop_table("processing_tasks")
    # ### end Alembic commands ###
